security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
         users:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/web/login$
            anonymous: false
            stateless: true
            json_login:
                check_path: api_login

        api:
            pattern: ^/api
            methods: [POST,PUT,DELETE]
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Security\ApiAuthenticator

    access_control:
         - { path: ^/web/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
